<a href="https://colab.research.google.com/github/sinhar1227/deep_learning/blob/main/ANN_Classification_Churning_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Explore the data

In [4]:
import pandas as pd

df = pd.read_csv('/content/sample_data/Churn_Modelling.csv')

In [5]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Drop irrelevant coloumns

In [6]:
irrelevant_columns = ['RowNumber', 'CustomerId', 'Surname']
df = df.drop(irrelevant_columns, axis=1)

In [7]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Encode non-numeric columns

In [8]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

### As there is only 3 uniques, so do one hot encoding for this column

In [9]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(df[['Geography']])
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
geo_features = onehot_encoder_geo.get_feature_names_out(['Geography'])
geo_features

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
df_geo = pd.DataFrame(geo_encoder.toarray(), columns=geo_features)
df_geo.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [12]:
df_new = pd.concat([df.drop('Geography',axis=1), df_geo], axis=1)
df_new.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,Female,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Female,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,Female,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

### Do the encoding for Gender column

In [13]:
from sklearn.preprocessing import LabelEncoder

labelencoder_gender = LabelEncoder()
gender_encoder = labelencoder_gender.fit_transform(df_new['Gender'])
df_new['Gender'] = gender_encoder

df_new.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

### Next step scaling the different columns, as we only need to do scaling for dependent coloumn, so first split the data into train and test

In [16]:
from sklearn.model_selection import train_test_split

x=df_new.drop('Exited', axis=1)
y=df_new[['Exited']]

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.20)

### Let scaled the data

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [20]:
X_test_scaled

array([[ 1.04977007,  0.8972481 , -0.04191259, ..., -1.002002  ,
         1.73900686, -0.57812007],
       [ 0.76637891,  0.8972481 ,  2.66212516, ...,  0.998002  ,
        -0.57504086, -0.57812007],
       [-0.53512123, -1.11451894,  0.82724241, ..., -1.002002  ,
         1.73900686, -0.57812007],
       ...,
       [ 0.32554822,  0.8972481 ,  0.4409513 , ...,  0.998002  ,
        -0.57504086, -0.57812007],
       [-0.70305673,  0.8972481 ,  0.63409685, ..., -1.002002  ,
        -0.57504086,  1.72974448],
       [-0.91297611,  0.8972481 , -0.04191259, ..., -1.002002  ,
        -0.57504086,  1.72974448]])

In [21]:
X_test

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
391,752,1,38,3,183102.29,1,1,1,71557.12,0.0,1.0,0.0
1387,725,1,66,4,86459.80,1,1,1,141476.56,1.0,0.0,0.0
4424,601,0,47,1,142802.02,1,1,1,57553.02,0.0,1.0,0.0
8107,560,1,50,3,0.00,2,1,0,84531.79,1.0,0.0,0.0
2670,598,0,64,9,0.00,1,0,1,13181.37,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6515,803,0,65,2,151659.52,2,0,1,6930.17,1.0,0.0,0.0
2356,625,0,37,4,142711.81,1,1,0,35625.41,0.0,1.0,0.0
8329,683,1,43,2,112499.42,2,1,0,30375.18,1.0,0.0,0.0
8575,585,1,45,0,0.00,2,0,0,189683.70,0.0,0.0,1.0
2233,565,1,38,0,122447.76,1,0,0,67339.34,0.0,0.0,1.0

In [36]:
X_test_scaled.shape

(2000, 12)

### Create ANN for classification

In [27]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [46]:
model=Sequential([
   Input((X_train_scaled.shape[1],)),
   Dense(32,activation='relu'),
   Dense(1,activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam')

In [47]:
model.fit(X_train_scaled, y_train,batch_size=5,epochs=50)

Epoch 1/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.4536
Epoch 2/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3831
Epoch 3/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3592
Epoch 4/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3505
Epoch 5/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3460
Epoch 6/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.3442
Epoch 7/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3422
Epoch 8/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3401
Epoch 9/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3388
Epoch 10/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3380
Epoch 11/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3359
Epoch 12/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3360
Epoch 13/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3340
Epoch 14/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.3333
Epoch 15/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3328
Epoch 16/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3327
Epoch 17/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3325
Epoch 18/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3317
Epoch 19/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3311
Epoch 20/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3291
Epoch 21/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3294
Epoch 22/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.3305
Epoch 23/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3301
Epoch 24/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3292
Epoch 25/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3302
Epoch 26/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3286
Epoch 27/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.3287
Epoch 28/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3274
Epoch 29/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3280
Epoch 30/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3268
Epoch 31/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3268
Epoch 32/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3266
Epoch 33/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3269
Epoch 34/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3265
Epoch 35/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3256
Epoch 36/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.3257
Epoch 37/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.3261
Epoch 38/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3238
Epoch 39/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3246
Epoch 40/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.3244
Epoch 41/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3249
Epoch 42/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3235
Epoch 43/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3243
Epoch 44/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3231
Epoch 45/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.3236
Epoch 46/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3231
Epoch 47/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3226
Epoch 48/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3231
Epoch 49/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.3218
Epoch 50/50
1600/1600 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 0.3220

In [44]:
y_train_predict=model.predict(X_train_scaled)
y_test_predict=model.predict(X_test_scaled)

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [45]:
y_train_predict

array([[0.09715308],
       [0.00813346],
       [0.03000793],
       ...,
       [0.01154989],
       [0.060538  ],
       [0.01449266]], dtype=float32)