<a href="https://colab.research.google.com/github/sinhar1227/deep_learning/blob/main/ANN_Classification_Churning_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Explore the data

In [51]:
import pandas as pd

df = pd.read_csv('/content/sample_data/Churn_Modelling.csv')

In [52]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Drop irrelevant coloumns

In [53]:
irrelevant_columns = ['RowNumber', 'CustomerId', 'Surname']
df = df.drop(irrelevant_columns, axis=1)

In [54]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Encode non-numeric columns

In [55]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

### As there is only 3 uniques, so do one hot encoding for this column

In [56]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(df[['Geography']])
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [57]:
geo_features = onehot_encoder_geo.get_feature_names_out(['Geography'])
geo_features

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [58]:
df_geo = pd.DataFrame(geo_encoder.toarray(), columns=geo_features)
df_geo.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [59]:
df_new = pd.concat([df.drop('Geography',axis=1), df_geo], axis=1)
df_new.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,Female,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Female,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,Female,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

### Do the encoding for Gender column

In [63]:
from sklearn.preprocessing import LabelEncoder

labelencoder_gender = LabelEncoder()
gender_encoder = labelencoder_gender.fit_transform(df_new['Gender'])
df_new['Gender'] = gender_encoder

df_new.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

### Next step scaling the different columns, as we only need to do scaling for dependent coloumn, so first split the data into train and test

In [65]:
from sklearn.model_selection import train_test_split

x=data.drop('Exited',axis=1)
y=data['Exited']

X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.20)

In [ ]:
X_train